apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: servicehub
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "changeme-root"
  MYSQL_USER: "servicehub"
  MYSQL_PASSWORD: "changeme-db"
