apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: servicehub
data:
  PORT: "3000"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_DATABASE: "servicehub"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  NODEMAILER_SERVICE: "gmail"
