apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: servicehub
type: Opaque
stringData:
  DB_USERNAME: "servicehub"
  DB_PASSWORD: "changeme-db"
  REDIS_PASSWORD: "changeme-redis"
  JWT_SECRET: "changeme-jwt-secret"
  JWT_ACCESS_SECRET: "changeme-jwt-access-secret"
  JWT_REFRESH_SECRET: "changeme-jwt-refresh-secret"
  REFRESH_SECRET: "changeme-jwt-refresh-secret"
  HASH_SALT: "10"
  NODEMAILER_AUTH_USER: "example@gmail.com"
  NODEMAILER_AUTH_PASS: "changeme-app-password"
